Algoritmo "Operadores Relacionais"

Var
valorA: inteiro
valorB: inteiro


Inicio
valorA <- 1;
valorB <- 2;

       Se(valorA > valorB)entao
          Escreval("maior")
       FimSe
          
       Se(valorA >= valorB)entao
          Escreval("maior ou igual")
       FimSe
          
       Se(valorA < valorB)entao
          Escreval("menor")
       FimSe
          
       Se(valorA<= valorB)entao
          Escreval("menor ou igual")
       FimSe

Fimalgoritmo